# Generated by Django 4.2.2 on 2023-10-29 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.IntegerField(default=0)),
                ('nome_cliente', models.CharField(max_length=60)),
                ('data_nascimento', models.DateField()),
                ('sexo_cliente', models.CharField(max_length=60)),
                ('email_cliente', models.CharField(max_length=60)),
                ('tel_cliente', models.CharField(default='', max_length=60)),
                ('cpf_cliente', models.CharField(default='', max_length=60)),
                ('profissao_cliente', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_for', models.IntegerField(default=0)),
                ('cnpj', models.IntegerField(default=0)),
                ('desc_for', models.CharField(max_length=60)),
                ('cod_produto', models.IntegerField(default=0)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_loja', models.IntegerField(default=0)),
                ('desc_loja', models.CharField(max_length=60)),
                ('desc_bairro', models.CharField(max_length=60)),
                ('desc_uf', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prod', models.IntegerField(default=0)),
                ('data_prod', models.DateField()),
                ('cod_grupo', models.IntegerField(default=0)),
                ('cod_dep', models.IntegerField(default=0)),
                ('desc_grupo', models.CharField(max_length=60)),
                ('desc_dep', models.CharField(max_length=60)),
                ('sku_prod', models.IntegerField(default=0)),
                ('nome_prod', models.CharField(max_length=60)),
                ('modelo_prod', models.CharField(max_length=60)),
                ('cor_prod', models.CharField(max_length=60)),
                ('tam_prod', models.CharField(max_length=60)),
                ('est_prod', models.CharField(max_length=60)),
                ('cod_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codfor', to='CarteiraApp.fornecedores')),
            ],
        ),
        migrations.CreateModel(
            name='Promocoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_promo', models.IntegerField(default=0)),
                ('nome_promo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vnd', models.DateField()),
                ('cpf_cliente', models.CharField(default='', max_length=60)),
                ('cod_pag', models.IntegerField(default=0)),
                ('valor_total', models.FloatField(max_length=60)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codcliente', to='CarteiraApp.cliente')),
                ('cod_loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codloja', to='CarteiraApp.loja')),
                ('cod_promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codpromo', to='CarteiraApp.promocoes')),
                ('sku_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skuprod', to='CarteiraApp.produtos')),
            ],
        ),
        migrations.AddField(
            model_name='loja',
            name='cod_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codprod', to='CarteiraApp.produtos'),
        ),
    ]
