# Generated by Django 4.2.2 on 2023-10-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarteiraApp', '0002_remove_fornecedores_cod_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='cnpj',
            field=models.CharField(max_length=60),
        ),
    ]
