# Generated by Django 4.2.2 on 2023-10-29 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarteiraApp', '0003_alter_fornecedores_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='cod_prod',
        ),
    ]
