# Generated by Django 4.2.2 on 2023-10-29 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarteiraApp', '0004_remove_loja_cod_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='cod_promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codpromo', to='CarteiraApp.promocoes'),
        ),
    ]
