# Generated by Django 4.2.2 on 2023-10-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarteiraApp', '0006_alter_vendas_cod_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='cod_vnd',
            field=models.IntegerField(default=0),
        ),
    ]
