# Generated by Django 4.2.2 on 2023-10-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarteiraApp', '0007_vendas_cod_vnd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_vnd',
            field=models.CharField(max_length=60),
        ),
    ]
