# Generated by Django 4.2.2 on 2023-10-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarteiraApp', '0008_alter_vendas_data_vnd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_vnd',
            field=models.DateField(),
        ),
    ]
