# Generated by Django 4.2.2 on 2023-07-24 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('placa', models.CharField(max_length=8)),
                ('carro', models.CharField(max_length=60)),
                ('serv', models.CharField(max_length=60)),
                ('vlr', models.CharField(max_length=6)),
                ('user', models.ForeignKey(default='a', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('carro', models.CharField(max_length=60)),
                ('valor', models.CharField(max_length=7)),
                ('litro', models.CharField(max_length=6)),
                ('km', models.CharField(max_length=6)),
                ('img', models.ImageField(upload_to='images', verbose_name='img')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='slug')),
                ('user', models.ForeignKey(default='a', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
