# Generated by Django 4.2.2 on 2023-07-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_urotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotas',
            name='serv1',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='rotas',
            name='serv2',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='rotas',
            name='vlr',
            field=models.IntegerField(),
        ),
    ]
