# Generated by Django 4.2.2 on 2023-07-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_rotas_serv1_rotas_serv2_alter_rotas_vlr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotas',
            name='serv1',
            field=models.CharField(max_length=60),
        ),
    ]
