# Generated by Django 4.2.2 on 2023-07-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_remove_rotas_serv1_remove_rotas_serv2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotas',
            name='vlr',
            field=models.CharField(max_length=6),
        ),
    ]
