# Generated by Django 4.2.2 on 2023-07-29 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crudapp', '0007_alter_rotas_vlr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abastecimentos',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='rotas',
            name='placa',
        ),
        migrations.AddField(
            model_name='rotas',
            name='serv1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='rotas',
            name='serv2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='rotas',
            name='status',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='urotas',
            name='carro',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='urotas',
            name='placa',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='abastecimentos',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crudapp.urotas'),
        ),
        migrations.AlterField(
            model_name='abastecimentos',
            name='img',
            field=models.ImageField(upload_to='bomba', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='abastecimentos',
            name='km',
            field=models.ImageField(upload_to='km', verbose_name='km'),
        ),
        migrations.CreateModel(
            name='RecibosPag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=60)),
                ('id_rota', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('rcb', models.ImageField(upload_to='recibos', verbose_name='rcb')),
                ('user', models.ForeignKey(default='a', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
