# Generated by Django 4.2.2 on 2023-07-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0009_rename_data_rotas_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimentos',
            name='carro',
            field=models.CharField(max_length=60),
        ),
    ]
