# Generated by Django 4.2.2 on 2023-07-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0011_rename_data_abastecimentos_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibospag',
            name='id_rota',
            field=models.IntegerField(blank=True),
        ),
    ]
