# Generated by Django 4.2.2 on 2023-07-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0012_alter_recibospag_id_rota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibospag',
            name='id_rota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
