# Generated by Django 4.2.2 on 2023-07-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0013_alter_recibospag_id_rota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibospag',
            name='id_rota',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
