# Generated by Django 4.2.2 on 2023-07-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0015_remove_recibospag_user_recibospag_moto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abastecimentos',
            name='litro',
        ),
        migrations.RemoveField(
            model_name='abastecimentos',
            name='valor',
        ),
        migrations.AddField(
            model_name='abastecimentos',
            name='nota',
            field=models.ImageField(default=None, upload_to='nf', verbose_name='nf'),
        ),
    ]
