# Generated by Django 4.2.2 on 2023-07-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0016_remove_abastecimentos_litro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimentos',
            name='nota',
            field=models.ImageField(upload_to='nf', verbose_name='nf'),
        ),
    ]
