# Generated by Django 4.2.2 on 2023-07-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0020_alter_recibospag_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibospag',
            name='dia',
            field=models.DateField(),
        ),
    ]
