# Generated by Django 4.2.2 on 2023-07-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0021_alter_recibospag_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibospag',
            name='dia',
            field=models.CharField(max_length=60),
        ),
    ]
