# Generated by Django 4.2.2 on 2023-07-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0022_alter_recibospag_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abastecimentos',
            name='user',
        ),
        migrations.AddField(
            model_name='abastecimentos',
            name='moto',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
