# Generated by Django 4.2.2 on 2023-08-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0023_remove_abastecimentos_user_abastecimentos_moto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abastecimentos',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='rotas',
            name='vlr',
        ),
        migrations.AddField(
            model_name='recibospag',
            name='desc',
            field=models.CharField(default='VAZIO', max_length=60),
        ),
        migrations.AddField(
            model_name='urotas',
            name='vlr',
            field=models.CharField(default='A', max_length=6),
        ),
    ]
