# Generated by Django 4.2.2 on 2023-08-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0024_remove_abastecimentos_nota_remove_rotas_vlr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibospag',
            name='desc',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='urotas',
            name='vlr',
            field=models.CharField(max_length=6),
        ),
    ]
