# Generated by Django 4.2.2 on 2023-08-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0025_alter_recibospag_desc_alter_urotas_vlr'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotas',
            name='vlr',
            field=models.CharField(default='a', max_length=6),
        ),
    ]
