# Generated by Django 4.2.2 on 2023-08-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0026_rotas_vlr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotas',
            name='vlr',
            field=models.CharField(max_length=6),
        ),
    ]
