# Generated by Django 4.2.2 on 2023-08-11 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0027_alter_rotas_vlr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urotas',
            name='placa',
        ),
    ]
