# Generated by Django 4.2.2 on 2023-08-14 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crudapp', '0028_remove_urotas_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotas',
            name='carro',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='rotas',
            name='dia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rotas',
            name='serv',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='rotas',
            name='user',
            field=models.ForeignKey(blank=True, default='a', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rotas',
            name='vlr',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
