# Generated by Django 4.2.2 on 2023-08-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0030_alter_rotas_carro_alter_rotas_dia_alter_rotas_serv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotas',
            name='serv1',
        ),
        migrations.RemoveField(
            model_name='rotas',
            name='serv2',
        ),
    ]
