# Generated by Django 4.2.2 on 2023-08-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0034_carros'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='photo',
            field=models.ImageField(null=True, upload_to='carros', verbose_name='photo'),
        ),
    ]
