# Generated by Django 4.2.2 on 2023-08-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0036_alter_carros_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urotas',
            name='carro',
        ),
        migrations.AlterField(
            model_name='urotas',
            name='user',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
