# Generated by Django 4.2.2 on 2023-08-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0038_alter_rotas_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60, null=True)),
                ('nome', models.CharField(max_length=60, null=True)),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('rg', models.CharField(max_length=12, null=True)),
                ('end', models.CharField(max_length=60, null=True)),
                ('cnh', models.ImageField(null=True, upload_to='docs', verbose_name='cnh')),
            ],
        ),
    ]
