# Generated by Django 4.2.2 on 2023-08-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0039_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(null=True, upload_to='docs', verbose_name='foto'),
        ),
    ]
