# Generated by Django 4.2.2 on 2023-09-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0041_alter_recibospag_desc_pag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urotas',
            name='vlr',
            field=models.IntegerField(max_length=6),
        ),
    ]
