# Generated by Django 4.2.2 on 2023-09-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0042_alter_urotas_vlr'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimentos',
            name='vlr',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='abastecimentos',
            name='img',
            field=models.ImageField(upload_to='bomba', verbose_name='bomba'),
        ),
    ]
