# Generated by Django 4.2.2 on 2023-09-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0043_abastecimentos_vlr_alter_abastecimentos_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimentos',
            name='status',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
