# Generated by Django 4.2.2 on 2023-09-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0044_abastecimentos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimentos',
            name='vlr',
            field=models.FloatField(max_length=4, null=True),
        ),
    ]
