# Generated by Django 4.2.2 on 2023-09-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0046_alter_rotas_vlr_alter_urotas_vlr'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moto', models.CharField(max_length=60)),
                ('data', models.CharField(max_length=10)),
                ('pdf', models.FileField(upload_to='notas', verbose_name='notas')),
            ],
        ),
    ]
