# Generated by Django 4.2.2 on 2023-09-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0048_rotas_empresa_urotas_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carros',
            options={'verbose_name': 'Modelos Cadastrados', 'verbose_name_plural': 'Modelos Cadastrados'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfil'},
        ),
        migrations.AlterModelOptions(
            name='rotas',
            options={'verbose_name': 'Rotas Diaria', 'verbose_name_plural': 'Rotas Diarias'},
        ),
        migrations.AlterModelOptions(
            name='urotas',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AddField(
            model_name='urotas',
            name='receber_vlr',
            field=models.FloatField(default=None, max_length=6),
        ),
    ]
