# Generated by Django 4.2.2 on 2023-11-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0053_alter_rotas_receber_vlr'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_selfie',
            field=models.ImageField(null=True, upload_to='self', verbose_name='selfie'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cnh',
            field=models.FileField(null=True, upload_to='cnhs', verbose_name='cnhs'),
        ),
    ]
